import { Table, Tag, Input } from 'antd';
import { useState, useEffect } from 'react'
import Head from 'next/head'

const {Search} = Input

const columns = [
  {title: 'ID', dataIndex: 'id' },
  {title: 'Category', dataIndex: 'category' },
  {title: 'Title', dataIndex: 'title' },
  {title: 'Description', dataIndex: 'description' },
  {title: 'Footer', dataIndex: 'footer' },
  {title: 'Tags', dataIndex: 'tags',
    render:(text, record) => (
      <ul>
        {(record.tags && record.tags.length > 0) && record.tags.map((tag, index) => (
          <li key={tag+index}>
            <Tag color="blue" >
              {tag}
            </Tag>
          </li>
        ))}
      </ul>
    )
  }
];

export default function Q2(props) {
  const { data } = props
  const [keyword, setKeyword] = useState('')
  const [filteredData, setFilteredData] = useState(data)

  const filterTable = (originalData, keyword) => {
    const filtered =  keyword 
      ? originalData.filter(d => {
          return (
            d.id && d.id.toString().toUpperCase().includes(keyword.toUpperCase()) ||
            d.category && d.category.toString().toUpperCase().includes(keyword.toUpperCase()) ||
            d.title && d.title.toUpperCase().includes(keyword.toUpperCase()) ||
            d.description && d.description.toUpperCase().includes(keyword.toUpperCase()) ||
            d.footer && d.footer.toUpperCase().includes(keyword.toUpperCase()) ||
            d.tags && d.tags.join(' ').toUpperCase().includes(keyword.toUpperCase())
          )
        })
      : originalData

    setFilteredData(filtered)
  }

  useEffect(() => {
    filterTable(data, keyword)
  }, [keyword, data])

  return (
    <>
      <Head>
        <title>Interview - Question 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{display:'flex', justifyContent:'space-between'}}>
        <h2 style={{textAlign: 'left'}}>    
          Question 2
        </h2>
        <Search 
          size="large"
          placeholder="Search" 
          value={keyword} 
          onChange={(e) => setKeyword(e.target.value)} 
          style={{ width: 400 }} 
        />
      </div>
      <Table rowKey='id' columns={columns} pagination={{defaultPageSize: 5, position:['bottom', 'left']}} dataSource={filteredData} />
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://screening.moduit.id/frontend/web/question/two')
  const data = await res.json()

  return {
    props: {
      data
    },
  }
}